version: '3' 
# Define the services/containers to be run
services:
  angular: 
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    container_name: angular
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - data-volume:/var/lib/a
    depends_on:
      - express
  express: 
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    container_name: express-api
    links:
      - database
    volumes:
      - data-volume:/var/lib/b
  database: 
    image: mongo 
    ports:
      - "27018:27017"   
volumes:
  data-volume:  